### ISSUE TITLE
Not working recently on installed repository?

### ISSUE THREAD

**Issue by jywarren** [hoodiehq/first-timers-bot#212]
Hi, we've noticed that in the past month or two (we aren't sure the exact time), `first-timers-bot` has stopped making issues for us. Is there a place we can look at a log or something to debug? 

For example, I opened this 2 days ago and didn't see an issue created: https://github.com/publiclab/plots2/tree/first-timers-tag-toggle

Thank you, we love this bot! ❤️ 🤖 🎉

**Comment by gr2m** [comment]
hmmm I’m not aware of any problem. You can see logs at https://zeit.co/deployments/first-timers-bot.now.sh/logs

**Comment by jywarren** [comment]
Ah, ok - i'm now seeing: `2019-03-13T18:49:01.226Z probot:first-timers:publiclab/plots2 TypeError: state.api.repos.getContent is not a function`

but oddly it had worked for our MapKnitter repository earlier today before we added a custom `.github/first-timers.yml` and `.github/FIRST_TIMERS_ISSUE_TEMPLATE.md` -- maybe our syntax is wrong? But we've used these before. 

* https://github.com/publiclab/mapknitter/blob/main/.github/first-timers.yml
* https://github.com/publiclab/mapknitter/blob/main/.github/first-timers-issue-template.md

**Comment by gr2m** [comment]
ah that might be related to the update of probot to v9, `.repos.getContent` was renamed to `repos.getContents` I think, I’m looking into it, sorry for the trouble!

**Comment by jywarren** [comment]
thank you so much!!! We are welcoming SO MANY PEOPLE lol (outreachy, GSoC,
others) and this bot is a real help! <3

**Comment by gr2m** [comment]
clearly the test setup is not very reliable, I found a few more other methods that needed to be renamed, it should:tm: all be good now

**Comment by jywarren** [comment]
Oh this is great, thanks - if you ping me when it's restarted, I can open a new branch to trigger and test?

**Comment by jywarren** [comment]
oh ok, testing!

**Comment by gr2m** [comment]
it’s not deployed yet, hold on

**Comment by jywarren** [comment]
haha sorry, i don't mean to rush, just trying to help. i'll take a deep breath! 😄

**Comment by gr2m** [comment]
okay can you try again now?

**Comment by jywarren** [comment]
It worked on MapKnitter! Thank you!

**Comment by jywarren** [comment]
And on `plots2` -- perfect! Thanks so much 👍 🎉 👐 ❤️

**Comment by jywarren** [comment]
Hi, just reopening this as FTB hasn't been running for us recently. 

I followed your advice to check the logs, and found:

https://zeit.co/first-timers-bot/first-timers-bot/tvczmldkah

```
2020-01-09T17:12:23.749Z probot:first-timers:publiclab/plots2 webhook received for branch "first-timers-authors-tooltip"
--
Jan 09 2020 12:12:23:8832020-01-09T17:12:23.749Z probot:first-timers:publiclab/plots2 getting branch "first-timers-authors-tooltip"
Jan 09 2020 12:12:24:1792020-01-09T17:12:24.099Z probot:first-timers:publiclab/plots2 "first-timers-authors-tooltip" branch found, last commit’s sha: a66f3f2d7e8da1ac6c906c65c7baee08ddf00e0a
Jan 09 2020 12:12:24:6542020-01-09T17:12:24.585Z probot:first-timers:publiclab/plots2 getting commit "a66f3f2d7e8da1ac6c906c65c7baee08ddf00e0a"
Jan 09 2020 12:12:24:704{ Deprecation: [@octokit/rest] "sha" parameter is deprecated for ".repos.getCommit()". Use "commit_sha" instead
Jan 09 2020 12:12:24:760    at Object.keys.forEach.key (/home/nowuser/src/node_modules/@octokit/rest/plugins/register-endpoints/register-endpoints.js:71:26)
Jan 09 2020 12:12:24:980    at Array.forEach (<anonymous>)
Jan 09 2020 12:12:25:070    at Object.patchedMethod [as getCommit] (/home/nowuser/src/node_modules/@octokit/rest/plugins/register-endpoints/register-endpoints.js:67:26)
Jan 09 2020 12:12:25:071    at getCommit (/home/nowuser/src/lib/get-commit.js:6:26)
Jan 09 2020 12:12:25:072    at <anonymous> name: 'Deprecation' }
Jan 09 2020 12:12:25:0742020-01-09T17:12:24.605Z probot:first-timers:publiclab/plots2 HttpError: Empty value for parameter 'ref': undefined
```

Especially `Jan 09 2020 12:12:25:0742020-01-09T17:12:24.605Z probot:first-timers:publiclab/plots2 HttpError: Empty value for parameter 'ref': undefined` -- do you know what that means? Does it relate to HTML in our project, like a `ref` HTML tag attribute that's empty?

It's for the branch in this PR: https://github.com/publiclab/plots2/pull/7160

**Comment by jywarren** [comment]
Oh sorry looks like I can't re-open. Opening a new one and referencing this from it. Thanks!
